[[modules-base]]
=== Base
Este módulo reune *componentes base* que entreguem funcionalidades básicas para outros componentes (mais uma vez, sejam
eles processos ou sistemas).

==== Archetypes
Modelos de projeto estruturados de acordo com a xref:reference-guide-architecture#reference-guide-architecture[Arquitetura
de Referência].

==== Build tools
A idéia deste módulo é suportar o processo de "build" das plataformas, provendo verificação de alguns aspectos de qualidade,
métricas e estilo do código-fonte das plataformas.

* Checkstyle
* Findbugs
* Formatter
* PMD

//==== Commons


==== Parent
Projeto base para todos os projetos, como o próprio nome diz, ele é o pai de todos os projetos. Define alguns aspectos
técnicos da estrutura de um projeto, por exemplo, onde são registradas as issues do projeto, onde está o código-fonte,
quais versões são "homologadas" para as dependências (bibliotecas) que devem ser utilizadas, como um projeto deve ser
compilado, testado e empacotado e, finalmente, quais repositórios de dependências podem ser acessados por todos os projetos.
